In [1]:
def convert_units(conversion_type, value):
    """
    Converts units based on the conversion type provided.

    Parameters:
    conversion_type (str): The type of conversion to perform.
                           Options: m_to_ft, ft_to_m, kg_to_lbs, lbs_to_kg,
                                    l_to_gal, gal_to_l
    value (float): The numeric value to convert.

    Returns:
    float: The converted value.
    """

    if conversion_type == "m_to_ft":
        return value * 3.28084
    elif conversion_type == "ft_to_m":
        return value / 3.28084
    elif conversion_type == "kg_to_lbs":
        return value * 2.20462
    elif conversion_type == "lbs_to_kg":
        return value / 2.20462
    elif conversion_type == "l_to_gal":
        return value * 0.264172
    elif conversion_type == "gal_to_l":
        return value / 0.264172
    else:
        raise ValueError("Unsupported conversion type.")


def main():
    print("Unit Conversion Program")
    print("-----------------------")
    print("Choose conversion type:")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")

    try:
        choice = int(input("Enter your choice (1-3): "))

        if choice == 1:
            print("Length Conversion:")
            print("a. Meters to Feet")
            print("b. Feet to Meters")
            option = input("Choose option (a/b): ").lower()

            value = float(input("Enter value: "))

            if option == "a":
                result = convert_units("m_to_ft", value)
                print(f"{value} meters = {result:.2f} feet")
            elif option == "b":
                result = convert_units("ft_to_m", value)
                print(f"{value} feet = {result:.2f} meters")
            else:
                print("Invalid option.")

        elif choice == 2:
            print("Weight Conversion:")
            print("a. Kilograms to Pounds")
            print("b. Pounds to Kilograms")
            option = input("Choose option (a/b): ").lower()

            value = float(input("Enter value: "))

            if option == "a":
                result = convert_units("kg_to_lbs", value)
                print(f"{value} kg = {result:.2f} lbs")
            elif option == "b":
                result = convert_units("lbs_to_kg", value)
                print(f"{value} lbs = {result:.2f} kg")
            else:
                print("Invalid option.")

        elif choice == 3:
            print("Volume Conversion:")
            print("a. Liters to Gallons")
            print("b. Gallons to Liters")
            option = input("Choose option (a/b): ").lower()

            value = float(input("Enter value: "))

            if option == "a":
                result = convert_units("l_to_gal", value)
                print(f"{value} L = {result:.2f} gallons")
            elif option == "b":
                result = convert_units("gal_to_l", value)
                print(f"{value} gallons = {result:.2f} L")
            else:
                print("Invalid option.")

        else:
            print("Invalid choice.")

    except ValueError:
        print("Error: Please enter a valid numeric value.")


# Run the program
main()

Unit Conversion Program
-----------------------
Choose conversion type:
1. Length
2. Weight
3. Volume


Enter your choice (1-3):  1


Length Conversion:
a. Meters to Feet
b. Feet to Meters


Choose option (a/b):  a
Enter value:  870


870.0 meters = 2854.33 feet


In [2]:
def calculate_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The sum of the numbers.
    """
    return sum(numbers)


def calculate_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The average of the numbers.
    """
    return sum(numbers) / len(numbers)


def find_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The maximum number.
    """
    return max(numbers)


def find_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The minimum number.
    """
    return min(numbers)


def main():
    print("Mathematical Operations Program")
    print("------------------------------")
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = int(input("Enter your choice (1-4): "))

        # Input numbers separated by spaces
        user_input = input("Enter numbers separated by spaces: ")
        numbers = [float(num) for num in user_input.split()]

        if len(numbers) == 0:
            raise ValueError("List is empty.")

        if choice == 1:
            result = calculate_sum(numbers)
            print("Sum =", result)

        elif choice == 2:
            result = calculate_average(numbers)
            print("Average =", result)

        elif choice == 3:
            result = find_maximum(numbers)
            print("Maximum =", result)

        elif choice == 4:
            result = find_minimum(numbers)
            print("Minimum =", result)

        else:
            print("Invalid choice.")

    except ValueError:
        print("Error: Please enter valid numbers and ensure the list is not empty.")


# Run program
main()

Mathematical Operations Program
------------------------------
Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum


Enter your choice (1-4):  4
Enter numbers separated by spaces:  3 5


Minimum = 3.0


In [3]:
def extract_every_other(lst):
    """
    Extracts every other element from a list starting from the first element.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list containing every other element.
    """
    return lst[::2]


# Example usage
numbers = [1, 2, 3, 4, 5, 6]
result = extract_every_other(numbers)
print("Output:", result)

Output: [1, 3, 5]


In [4]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from the given list starting at index 'start'
    and ending at index 'end' (inclusive).

    Parameters:
    lst (list): The original list.
    start (int): Starting index.
    end (int): Ending index (inclusive).

    Returns:
    list: The extracted sublist.
    """
    return lst[start:end + 1]


# Example usage
numbers = [1, 2, 3, 4, 5, 6]
result = get_sublist(numbers, 2, 4)
print("Output:", result)

Output: [3, 4, 5]


In [5]:
def reverse_list(lst):
    """
    Reverses a list using slicing.

    Parameters:
    lst (list): The input list.

    Returns:
    list: The reversed list.
    """
    return lst[::-1]


# Example usage
numbers = [1, 2, 3, 4, 5]
result = reverse_list(numbers)
print("Output:", result)

Output: [5, 4, 3, 2, 1]


In [6]:
def remove_first_last(lst):
    """
    Removes the first and last elements from a list using slicing.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list without the first and last elements.
    """
    return lst[1:-1]  # Slice from index 1 to second last element


# Example usage
numbers = [1, 2, 3, 4, 5]
result = remove_first_last(numbers)
print("Output:", result)


Output: [2, 3, 4]


In [7]:
def get_first_n(lst, n):
    """
    Extracts the first n elements from a list using slicing.

    Parameters:
    lst (list): The input list.
    n (int): Number of elements to extract.

    Returns:
    list: A new list containing the first n elements.
    """
    return lst[:n]  # Slice from start to n elements


# Example usage
numbers = [1, 2, 3, 4, 5]
result = get_first_n(numbers, 3)
print("Output:", result)

Output: [1, 2, 3]


In [8]:
def get_last_n(lst, n):
    """
    Extracts the last n elements from a list using slicing.

    Parameters:
    lst (list): The input list.
    n (int): Number of elements to extract from the end.

    Returns:
    list: A new list containing the last n elements.
    """
    return lst[-n:]  # Slice from the last n elements


# Example usage
numbers = [1, 2, 3, 4, 5]
result = get_last_n(numbers, 2)
print("Output:", result)

Output: [4, 5]


In [9]:
def reverse_skip(lst):
    """
    Extracts every second element from a list starting from the second-to-last element,
    moving backward.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list with elements in reverse order, skipping one in between.
    """
    return lst[-2::-2]  # Start from second-to-last, step -2 backwards


# Example usage
numbers = [1, 2, 3, 4, 5, 6]
result = reverse_skip(numbers)
print("Output:", result)

Output: [5, 3, 1]


In [10]:
def flatten(lst):
    """
    Flattens a nested list into a single list with all elements in one dimension.

    Parameters:
    lst (list): A nested list (list of lists).

    Returns:
    list: A flattened list containing all elements.
    """
    flat_list = []
    for sublist in lst:
        for item in sublist:
            flat_list.append(item)
    return flat_list


# Example usage
nested_list = [[1, 2], [3, 4], [5]]
result = flatten(nested_list)
print("Output:", result)

Output: [1, 2, 3, 4, 5]


In [11]:
def access_nested_element(lst, indices):
    """
    Accesses a specific element from a nested list given a list of indices.

    Parameters:
    lst (list): The nested list.
    indices (list): A list of indices specifying the position of the element.

    Returns:
    The element at the specified position.
    """
    element = lst
    for index in indices:
        element = element[index]
    return element


# Example usage
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(nested_list, indices)
print("Output:", result)

Output: 6


In [12]:
def sum_nested(lst):
    """
    Recursively calculates the sum of all numbers in a nested list, regardless of depth.

    Parameters:
    lst (list): The nested list.

    Returns:
    int/float: Sum of all elements in the nested list.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)  # Recursively sum nested lists
        else:
            total += item
    return total


# Example usage
nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)
print("Output:", result)

Output: 21


In [13]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
    lst (list): The nested list.
    elem: The element to remove.

    Returns:
    list: A new nested list with the element removed.
    """
    new_list = []
    for sublist in lst:
        if isinstance(sublist, list):
            filtered_sublist = [x for x in sublist if x != elem]
            new_list.append(filtered_sublist)
        else:
            # Handle case where lst itself has non-list elements
            if sublist != elem:
                new_list.append(sublist)
    return new_list


# Example usage
nested_list = [[1, 2], [3, 2], [4, 5]]
element_to_remove = 2
result = remove_element(nested_list, element_to_remove)
print("Output:", result)

Output: [[1], [3], [4, 5]]


In [14]:
def find_max(lst):
    """
    Finds the maximum element in a nested list regardless of depth.

    Parameters:
    lst (list): The nested list.

    Returns:
    int/float: The maximum element in the nested list.
    """
    maximum = float('-inf')  # Start with smallest possible value
    for item in lst:
        if isinstance(item, list):
            maximum = max(maximum, find_max(item))  # Recursively find max
        else:
            maximum = max(maximum, item)
    return maximum


# Example usage
nested_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(nested_list)
print("Output:", result)

Output: 6


In [15]:
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list.

    Parameters:
    lst (list): The nested list.
    elem: The element to count.

    Returns:
    int: The number of occurrences of the element in the nested list.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)  # Recursively count in sublists
        elif item == elem:
            count += 1
    return count


# Example usage
nested_list = [[1, 2], [2, 3], [2, 4]]
element_to_count = 2
result = count_occurrences(nested_list, element_to_count)
print("Output:", result)

Output: 3


In [16]:
def deep_flatten(lst):
    """
    Recursively flattens a deeply nested list into a single list, regardless of depth.

    Parameters:
    lst (list): The deeply nested list.

    Returns:
    list: A flattened list containing all elements.
    """
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))  # Recursively flatten sublists
        else:
            flat_list.append(item)
    return flat_list


# Example usage
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)
print("Output:", result)

Output: [1, 2, 3, 4, 5, 6, 7, 8]


In [17]:
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Parameters:
    lst (list): The nested list.

    Returns:
    float: The average of all elements.
    """
    def flatten(lst):
        """Helper function to flatten the nested list completely."""
        flat_list = []
        for item in lst:
            if isinstance(item, list):
                flat_list.extend(flatten(item))
            else:
                flat_list.append(item)
        return flat_list

    flat_list = flatten(lst)
    if not flat_list:
        return 0  # Avoid division by zero
    return sum(flat_list) / len(flat_list)


# Example usage
nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)
print("Output:", result)

Output: 3.5


In [21]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty 2x2 array:\n", empty_array, "\n")

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("2. All-one 4x2 array:\n", ones_array, "\n")

# 3. Return a new array of given shape and type, filled with fill value
fill_value = 7  # Example fill value
filled_array = np.full((3, 3), fill_value, dtype=int)
print("3. 3x3 array filled with 7:\n", filled_array, "\n")

# 4. Return a new array of zeros with same shape and type as a given array
given_array = np.array([[5, 10], [15, 20]])
zeros_like_array = np.zeros_like(given_array)
print("4. Zeros like given array:\n", zeros_like_array, "\n")

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("5. Ones like given array:\n", ones_like_array, "\n")

# 6. Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("6. Numpy array from list [1,2,3,4]:\n", array_from_list)

1. Empty 2x2 array:
 [[0. 0.]
 [0. 0.]] 

2. All-one 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 

3. 3x3 array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]] 

4. Zeros like given array:
 [[0 0]
 [0 0]] 

5. Ones like given array:
 [[1 1]
 [1 1]] 

6. Numpy array from list [1,2,3,4]:
 [1 2 3 4]


In [19]:
!python3 --version

Python 3.13.2


In [20]:
!python3 -m pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 14.8 MB/s eta 0:00:00a 0:00:01

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip


In [22]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
array_10_49 = np.arange(10, 50)
print("1. Array from 10 to 49:\n", array_10_49, "\n")

# 2. Create a 3x3 matrix with values from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("2. 3x3 matrix from 0 to 8:\n", matrix_3x3, "\n")

# 3. Create a 3x3 identity matrix
identity_3x3 = np.eye(3)
print("3. 3x3 identity matrix:\n", identity_3x3, "\n")

# 4. Create a random array of size 30 and find the mean
random_array_30 = np.random.random(30)
mean_30 = random_array_30.mean()
print("4. Random array of size 30:\n", random_array_30)
print("Mean of array:", mean_30, "\n")

# 5. Create a 10x10 array with random values and find min and max
random_10x10 = np.random.random((10, 10))
min_val = random_10x10.min()
max_val = random_10x10.max()
print("5. 10x10 random array:\n", random_10x10)
print("Min:", min_val, "Max:", max_val, "\n")

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # 5th element (index 4)
print("6. Zero array with 5th element = 1:\n", zero_array, "\n")

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("7. Reversed array:\n", reversed_arr, "\n")

# 8. Create a 2D array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("8. 2D array with 1 on border and 0 inside:\n", border_array, "\n")

# 9. Create an 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("9. 8x8 Checkerboard pattern:\n", checkerboard)

1. Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

2. 3x3 matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

3. 3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

4. Random array of size 30:
 [0.42693147 0.80848221 0.98418135 0.73185558 0.89318988 0.5246733
 0.13695984 0.61256905 0.57232373 0.16985367 0.9683151  0.86671929
 0.54692434 0.68455548 0.6647686  0.7853568  0.4288808  0.99682272
 0.14017941 0.8061719  0.78319359 0.00658358 0.79727803 0.36734566
 0.1368725  0.80406148 0.16312073 0.41317035 0.97536098 0.77130006]
Mean of array: 0.5989333828635087 

5. 10x10 random array:
 [[0.14706    0.35274303 0.67768926 0.29212152 0.94252242 0.07177846
  0.31084912 0.64182583 0.52083807 0.56500351]
 [0.8526444  0.79383184 0.28938301 0.61954939 0.03793557 0.93625562
  0.05491866 0.38046176 0.27694371 0.30505301]
 [0.39823345 0.72348205 0.8176708  0.18351582 0.7224518  0.43268619
  0.92

In [23]:
import numpy as np

# Arrays given
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("1. x + y:\n", add_xy, "\n")

# 2. Subtract the two arrays
sub_xy = x - y
print("2. x - y:\n", sub_xy, "\n")

# 3. Multiply the array with an integer (example: 3)
mul_x = x * 3
print("3. x * 3:\n", mul_x, "\n")

# 4. Square each element of the array
square_x = x ** 2
print("4. Square of x:\n", square_x, "\n")

# 5. Dot product
dot_vw = np.dot(v, w)      # Dot product of vectors
dot_xv = np.dot(x, v)      # Dot product of matrix x and vector v
dot_xy = np.dot(x, y)      # Dot product of matrices x and y

print("5a. Dot product of v and w:", dot_vw)
print("5b. Dot product of x and v:\n", dot_xv)
print("5c. Dot product of x and y:\n", dot_xy, "\n")

# 6. Concatenate
concat_xy_row = np.concatenate((x, y), axis=0)   # along row
concat_vw_col = np.concatenate((v.reshape(-1,1), w.reshape(-1,1)), axis=1)  # column

print("6a. Concatenate x and y along row:\n", concat_xy_row)
print("6b. Concatenate v and w along column:\n", concat_vw_col, "\n")

# 7. Concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    concat_xv_error = str(e)

print("7. Attempt to concatenate x and v along row gives error:\n", concat_xv_error)

1. x + y:
 [[ 6  8]
 [10 13]] 

2. x - y:
 [[-4 -4]
 [-4 -3]] 

3. x * 3:
 [[ 3  6]
 [ 9 15]] 

4. Square of x:
 [[ 1  4]
 [ 9 25]] 

5a. Dot product of v and w: 219
5b. Dot product of x and v:
 [29 77]
5c. Dot product of x and y:
 [[19 22]
 [50 58]] 

6a. Concatenate x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
6b. Concatenate v and w along column:
 [[ 9 11]
 [10 12]] 

7. Attempt to concatenate x and v along row gives error:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [24]:
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)  # Inverse of A
identity = np.dot(A, A_inv)
print("1. A * A^-1 =\n", identity)
print("Check if identity matrix:\n", np.allclose(identity, np.eye(2)), "\n")  # True if approx equal

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("2. AB =\n", AB)
print("   BA =\n", BA)
print("Check if AB == BA:", np.array_equal(AB, BA), "\n")  # Should be False

# 3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)
B_TA_T = np.dot(B.T, A.T)
print("3. (AB)^T =\n", AB_T)
print("   B^T * A^T =\n", B_TA_T)
print("Check equality:", np.allclose(AB_T, B_TA_T), "\n")  # Should be True

# --- Solve System of Linear Equations ---
# Equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Represent in matrix form AX = B
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])

B_eq = np.array([-1, -3, 9])

# Solve using inverse method
X = np.dot(np.linalg.inv(A_eq), B_eq)
print("Solution using inverse method:", X, "\n")

# Verify solution using np.linalg.solve (recommended method)
X_verify = np.linalg.solve(A_eq, B_eq)
print("Solution using np.linalg.solve:", X_verify)

1. A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Check if identity matrix:
 True 

2. AB =
 [[23 13]
 [51 29]]
   BA =
 [[36 44]
 [13 16]]
Check if AB == BA: False 

3. (AB)^T =
 [[23 51]
 [13 29]]
   B^T * A^T =
 [[23 51]
 [13 29]]
Check equality: True 

Solution using inverse method: [ 2.  1. -2.] 

Solution using np.linalg.solve: [ 2.  1. -2.]


In [25]:
import numpy as np
import time

# --- Using Python Lists ---
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

# Measure time for element-wise addition with Python lists
start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
python_time = end_time - start_time
print(f"Time taken for element-wise addition using Python lists: {python_time:.5f} seconds\n")

# --- Using NumPy Arrays ---
arr1 = np.arange(size)
arr2 = np.arange(size)

# Measure time for element-wise addition with NumPy arrays
start_time = time.time()
result_array = arr1 + arr2
end_time = time.time()
numpy_time = end_time - start_time
print(f"Time taken for element-wise addition using NumPy arrays: {numpy_time:.5f} seconds\n")

# Compare speedup
speedup = python_time / numpy_time
print(f"NumPy is approximately {speedup:.2f} times faster than plain Python lists.")

Time taken for element-wise addition using Python lists: 0.05724 seconds

Time taken for element-wise addition using NumPy arrays: 0.00165 seconds

NumPy is approximately 34.75 times faster than plain Python lists.


In [26]:
import numpy as np
import time

# Size of arrays
size = 1_000_000

# --- Using Python Lists ---
list1 = list(range(size))
list2 = list(range(size))

# Measure time for element-wise multiplication with Python lists
start_time = time.time()
result_list_mul = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
python_mul_time = end_time - start_time
print(f"Time taken for element-wise multiplication using Python lists: {python_mul_time:.5f} seconds\n")

# --- Using NumPy Arrays ---
arr1 = np.arange(size)
arr2 = np.arange(size)

# Measure time for element-wise multiplication with NumPy arrays
start_time = time.time()
result_array_mul = arr1 * arr2
end_time = time.time()
numpy_mul_time = end_time - start_time
print(f"Time taken for element-wise multiplication using NumPy arrays: {numpy_mul_time:.5f} seconds\n")

# Compare speedup
speedup_mul = python_mul_time / numpy_mul_time
print(f"NumPy is approximately {speedup_mul:.2f} times faster than plain Python lists for multiplication.")

Time taken for element-wise multiplication using Python lists: 0.04401 seconds

Time taken for element-wise multiplication using NumPy arrays: 0.00163 seconds

NumPy is approximately 27.07 times faster than plain Python lists for multiplication.


In [27]:
import numpy as np
import time

# Size of arrays
size = 1_000_000

# --- Using Python Lists ---
list1 = list(range(size))
list2 = list(range(size))

# Measure time for dot product with Python lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()
python_dot_time = end_time - start_time
print(f"Time taken for dot product using Python lists: {python_dot_time:.5f} seconds\n")

# --- Using NumPy Arrays ---
arr1 = np.arange(size)
arr2 = np.arange(size)

# Measure time for dot product with NumPy arrays
start_time = time.time()
dot_product_array = np.dot(arr1, arr2)
end_time = time.time()
numpy_dot_time = end_time - start_time
print(f"Time taken for dot product using NumPy arrays: {numpy_dot_time:.5f} seconds\n")

# Compare speedup
speedup_dot = python_dot_time / numpy_dot_time
print(f"NumPy is approximately {speedup_dot:.2f} times faster than Python lists for dot product.")

Time taken for dot product using Python lists: 0.05682 seconds

Time taken for dot product using NumPy arrays: 0.00055 seconds

NumPy is approximately 104.07 times faster than Python lists for dot product.


In [ ]:
import numpy as np
import time

# Size of matrices
size = 1000

# --- Using Python Lists ---
# Create two 1000x1000 matrices as lists of lists
matrix1 = [[i + j for j in range(size)] for i in range(size)]
matrix2 = [[i - j for j in range(size)] for i in range(size)]

# Measure time for matrix multiplication with Python lists
start_time = time.time()
result_matrix = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(size)) 
                  for j in range(size)] 
                  for i in range(size)]
end_time = time.time()
python_matmul_time = end_time - start_time
print(f"Time taken for 1000x1000 matrix multiplication using Python lists: {python_matmul_time:.5f} seconds\n")

# --- Using NumPy Arrays ---
# Create NumPy arrays
np_matrix1 = np.arange(size*size).reshape(size, size)
np_matrix2 = np.arange(size*size).reshape(size, size)

# Measure time for matrix multiplication with NumPy
start_time = time.time()
np_result = np.dot(np_matrix1, np_matrix2)  # or np_matrix1 @ np_matrix2
end_time = time.time()
numpy_matmul_time = end_time - start_time
print(f"Time taken for 1000x1000 matrix multiplication using NumPy arrays: {numpy_matmul_time:.5f} seconds\n")

# Speedup
speedup = python_matmul_time / numpy_matmul_time
print(f"NumPy is approximately {speedup:.2f} times faster than Python lists for matrix multiplication.")